package gov.nih.nci.cananolab.domain.particle;
// Generated Oct 17, 2017 2:18:23 PM by Hibernate Tools 4.0.1.Final

import gov.nih.nci.cananolab.domain.common.ExperimentConfig;
import gov.nih.nci.cananolab.domain.common.Finding;
import gov.nih.nci.cananolab.domain.common.PointOfContact;
import gov.nih.nci.cananolab.domain.common.Protocol;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Characterization generated by hbm2java
 */
public class Characterization implements java.io.Serializable {

	private Long id;
	private String analysisConclusion;
	private String assayType;
	private String createdBy;
	private Date createdDate;
	private Date date;
	private String designMethodsDescription;
	private Protocol protocol;
	private Set<ExperimentConfig> experimentConfigCollection = new HashSet<ExperimentConfig>(0);
	private PointOfContact pointOfContact;
	private Set<Finding> findingCollection = new HashSet<Finding>(0);
	private Sample sample;

	public Characterization() {
	}

	public Characterization(String analysisConclusion, String assayType, String createdBy, Date createdDate, Date date,
			String designMethodsDescription, Protocol protocol, Set experimentConfigCollection,
			PointOfContact pointOfContact, Set findingCollection, Sample sample) {
		this.analysisConclusion = analysisConclusion;
		this.assayType = assayType;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.date = date;
		this.designMethodsDescription = designMethodsDescription;
		this.protocol = protocol;
		this.experimentConfigCollection = experimentConfigCollection;
		this.pointOfContact = pointOfContact;
		this.findingCollection = findingCollection;
		this.sample = sample;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAnalysisConclusion() {
		return this.analysisConclusion;
	}

	public void setAnalysisConclusion(String analysisConclusion) {
		this.analysisConclusion = analysisConclusion;
	}

	public String getAssayType() {
		return this.assayType;
	}

	public void setAssayType(String assayType) {
		this.assayType = assayType;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getDesignMethodsDescription() {
		return this.designMethodsDescription;
	}

	public void setDesignMethodsDescription(String designMethodsDescription) {
		this.designMethodsDescription = designMethodsDescription;
	}

	public Protocol getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	public Set<ExperimentConfig> getExperimentConfigCollection() {
		return this.experimentConfigCollection;
	}

	public void setExperimentConfigCollection(Set<ExperimentConfig> experimentConfigCollection) {
		this.experimentConfigCollection = experimentConfigCollection;
	}

	public PointOfContact getPointOfContact() {
		return this.pointOfContact;
	}

	public void setPointOfContact(PointOfContact pointOfContact) {
		this.pointOfContact = pointOfContact;
	}

	public Set<Finding> getFindingCollection() {
		return this.findingCollection;
	}

	public void setFindingCollection(Set<Finding> findingCollection) {
		this.findingCollection = findingCollection;
	}

	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

}
