package gov.nih.nci.cananolab.domain.particle;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import gov.nih.nci.cananolab.domain.common.Protocol;

import gov.nih.nci.cananolab.domain.common.PurificationConfig;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SynthesisPurification generated by hbm2java
 */
public class SynthesisPurification implements java.io.Serializable {

	private Long synthesisPurificationPkId;
	private Protocol protocol;
	private String type;
	private String methodName;
	private String designMethodDescription;
	private String createdBy;
	private Date createdDate;
	private Integer yield;
	private Set<SynthesisPurity> purities = new HashSet<SynthesisPurity>(0);
	private Set<PurificationConfig> purificationConfigs = new HashSet<PurificationConfig>(0);

	public SynthesisPurification() {
	}

	public SynthesisPurification(Long synthesisPurificationPkId, Protocol protocol,
								  String createdBy, Date createdDate) {
		this.synthesisPurificationPkId = synthesisPurificationPkId;
		this.protocol = protocol;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public SynthesisPurification(Long synthesisPurificationPkId, Protocol protocol,
								  String type, String methodName, String designMethodDescription, String createdBy,
								 Date createdDate, Set<SynthesisPurity> purities, Set<PurificationConfig> purificationConfigs, Integer yield) {
		this.synthesisPurificationPkId = synthesisPurificationPkId;
		this.protocol = protocol;
		this.type = type;
		this.methodName = methodName;
		this.designMethodDescription = designMethodDescription;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.purities = purities;
		this.purificationConfigs = purificationConfigs;
		this.yield = yield;
	}

	public Long getId() {
		return this.synthesisPurificationPkId;
	}

	public void setId(Long synthesisFuncPurificationPkId) {
		this.synthesisPurificationPkId = synthesisFuncPurificationPkId;
	}

	public Protocol getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	public String getDesignMethodDescription() {
		return this.designMethodDescription;
	}

	public void setDesignMethodDescription(String designMethodDescription) {
		this.designMethodDescription = designMethodDescription;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set<SynthesisPurity> getPurities() {
		return this.purities;
	}

	public void setPurities(Set<SynthesisPurity> purities) {
		this.purities = purities;
	}

	public Set<PurificationConfig> getPurificationConfigs() {
		return this.purificationConfigs;
	}

	public void setPurificationConfigs(Set<PurificationConfig> purificationConfigs) {
		this.purificationConfigs = purificationConfigs;
	}

	public void setYield(Integer yield) {this.yield = yield;}

	public Integer getYield(){return yield;}

}
