package gov.nih.nci.cananolab.domain.particle;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import java.io.Serializable;
import java.util.Set;


/**
 * Synthesis generated by hbm2java
 */
public class Synthesis implements Serializable {

	private Long synthesisPkId;
	private Sample sample;
	private Set<SynthesisMaterial> synthesisMaterials;
	private Set<SynthesisFunctionalization> synthesisFunctionalizations;
	private Set<SynthesisPurification> synthesisPurifications;


	public Set<SynthesisPurification> getSynthesisPurifications() {
		return synthesisPurifications;
	}

	public void setSynthesisPurifications(Set<SynthesisPurification> synthesisPurifications) {
		this.synthesisPurifications = synthesisPurifications;
	}

	public Set<SynthesisFunctionalization> getSynthesisFunctionalizations() {
		return synthesisFunctionalizations;
	}

	public void setSynthesisFunctionalizations(Set<SynthesisFunctionalization> synthesisFunctionalizationsBySynthesisPkId) {
		this.synthesisFunctionalizations = synthesisFunctionalizationsBySynthesisPkId;
	}

	public Set<SynthesisMaterial> getSynthesisMaterials() {
		return synthesisMaterials;
	}

	public void setSynthesisMaterials(Set<SynthesisMaterial> synthesisMaterialsBySynthesisPkId) {
		this.synthesisMaterials = synthesisMaterialsBySynthesisPkId;
	}

	public Sample getSample() {
		return sample;
	}

	public void setSample(Sample sampleBySamplePkId) {
		this.sample = sampleBySamplePkId;
	}


	public Long getId() {
		return synthesisPkId;
	}

	public void setId(Long synthesisPkId) {
		this.synthesisPkId = synthesisPkId;
	}


}
