package gov.nih.nci.cananolab.domain.particle;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import gov.nih.nci.cananolab.domain.common.File;
import gov.nih.nci.cananolab.domain.common.PurityDatum;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Purity generated by hbm2java
 */
public class SynthesisPurity implements java.io.Serializable {

	private Long purityPkId;
	private SynthesisPurification synthesisPurification;
	private String createdBy;
	private Date createdDate;
	private Set<File> files = new HashSet<File>(0);
	private Set<PurityDatum> purityDatums = new HashSet<PurityDatum>(0);

	public SynthesisPurity() {
	}

	public SynthesisPurity(Long purityPkId, SynthesisPurification SynthesisPurification, String createdBy,
						   Date createdDate) {
		this.purityPkId = purityPkId;
		this.synthesisPurification = SynthesisPurification;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public SynthesisPurity(long purityPkId, SynthesisPurification SynthesisPurification, String createdBy,
						   Date createdDate, Set files, Set purityDatums) {
		this.purityPkId = purityPkId;
		this.synthesisPurification = SynthesisPurification;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.files = files;
		this.purityDatums = purityDatums;
	}

	public Long getId() {
		return this.purityPkId;
	}

	public void setId(Long purityPkId) {
		this.purityPkId = purityPkId;
	}

	public SynthesisPurification getSynthesisPurification() {
		return this.synthesisPurification;
	}

	public void setSynthesisPurification(SynthesisPurification SynthesisPurification) {
		this.synthesisPurification = SynthesisPurification;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Set<File> getFiles() {
		return this.files;
	}

	public void setFiles(Set<File> files) {
		this.files = files;
	}

	public Set<PurityDatum> getPurityDatumCollection() {
		return this.purityDatums;
	}

	public void setPurityDatumCollection(Set<PurityDatum> purityDatums) {
		this.purityDatums = purityDatums;
	}

}
