package gov.nih.nci.cananolab.domain.particle;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import gov.nih.nci.cananolab.domain.common.File;
import gov.nih.nci.cananolab.domain.common.Protocol;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SynthesisMaterials generated by hbm2java
 */
public class SynthesisMaterial implements Serializable {

	private Long synthesisMaterialsPkId;
	private Protocol protocol;
	private Synthesis synthesis;
	private String description;
	private Date createdDate;
	private String createdBy;
	private Set<SynthesisMaterialElement> synthesisMaterialElements = new HashSet<SynthesisMaterialElement>(0);
    private Set<File> fileCollection;

    public Set<File> getFiles() {
        return fileCollection;
    }

    public void setFiles(Set<File> fileCollection) {
        this.fileCollection = fileCollection;
    }

    public SynthesisMaterial() {
	}

	public SynthesisMaterial(Long synthesisMaterialsPkId, Synthesis synthesis, Date createdDate, String createdBy) {
		this.synthesisMaterialsPkId = synthesisMaterialsPkId;
		this.synthesis = synthesis;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
	}

	public SynthesisMaterial(Long synthesisMaterialsPkId, Protocol protocol, Synthesis synthesis, String description,
							 Date createdDate, String createdBy, Set<SynthesisMaterialElement> synthesisMaterialElements, Set<File> fileCollection) {
		this.synthesisMaterialsPkId = synthesisMaterialsPkId;
		this.protocol = protocol;
		this.synthesis = synthesis;
		this.description = description;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.synthesisMaterialElements = synthesisMaterialElements;
		this.fileCollection=fileCollection;
	}

	public Long getId() {
		return this.synthesisMaterialsPkId;
	}

	public void setId(Long synthesisMaterialsPkId) {
		this.synthesisMaterialsPkId = synthesisMaterialsPkId;
	}

	public Protocol getProtocol() {
		return this.protocol;
	}

	public void setProtocol(Protocol protocol) {
		this.protocol = protocol;
	}

	public Synthesis getSynthesis() {
		return this.synthesis;
	}

	public void setSynthesis(Synthesis synthesis) {
		this.synthesis = synthesis;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Set<SynthesisMaterialElement> getSynthesisMaterialElements() {
		return this.synthesisMaterialElements;
	}

	public void setSynthesisMaterialElements(Set<SynthesisMaterialElement> synthesisMaterialElements) {
		this.synthesisMaterialElements = synthesisMaterialElements;
	}

}
