package gov.nih.nci.cananolab.domain.agentmaterial;
// Generated Oct 17, 2017 2:18:23 PM by Hibernate Tools 4.0.1.Final

import gov.nih.nci.cananolab.domain.particle.ActivationMethod;
import gov.nih.nci.cananolab.domain.particle.SampleComposition;
import java.util.Date;
import java.util.HashSet;

/**
 * Antibody generated by hbm2java
 */
public class Antibody extends gov.nih.nci.cananolab.domain.particle.FunctionalizingEntity
		implements java.io.Serializable {

	private String isotype;
	private String species;
	private String type;

	public Antibody() {
	}

	public Antibody(String createdBy, Date createdDate, String description, String molecularFormula,
			String molecularFormulaType, String name, float value, String valueUnit, String pubChemDataSourceName,
			long pubChemId, HashSet chemicalAssociationACollection, HashSet chemicalAssociationBCollection, HashSet fileCollection,
			SampleComposition sampleComposition, ActivationMethod activationMethod, HashSet functionCollection,
			String isotype, String species, String type) {
		super(createdBy, createdDate, description, molecularFormula, molecularFormulaType, name, value, valueUnit,
				pubChemDataSourceName, pubChemId, chemicalAssociationACollection, chemicalAssociationBCollection,
				fileCollection, sampleComposition, activationMethod, functionCollection);
		this.isotype = isotype;
		this.species = species;
		this.type = type;
	}

	public String getIsotype() {
		return this.isotype;
	}

	public void setIsotype(String isotype) {
		this.isotype = isotype;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
