package gov.nih.nci.cananolab.domain.common;
// Generated Oct 17, 2017 2:18:23 PM by Hibernate Tools 4.0.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Datum generated by hbm2java
 */
public class Datum implements java.io.Serializable {

	private Long id;
	private String createdBy;
	private Date createdDate;
	private String name;
	private Float value;
	private String valueType;
	private String valueUnit;
	private String operand;
	private Set<Condition> conditionCollection = new HashSet<Condition>(0);
	private Finding finding;
	private File file;

	public Datum() {
	}

	public Datum(String createdBy, Date createdDate, String name, Float value, String valueType, String valueUnit,
			String operand, Set<Condition> conditionCollection, Finding finding, File file) {
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.name = name;
		this.value = value;
		this.valueType = valueType;
		this.valueUnit = valueUnit;
		this.operand = operand;
		this.conditionCollection = conditionCollection;
		this.finding = finding;
		this.file = file;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getValue() {
		return this.value;
	}
	

	public void setValue(Float value) {
		this.value = value;
	}

	public String getValueType() {
		return this.valueType;
	}

	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	public String getValueUnit() {
		return this.valueUnit;
	}

	public void setValueUnit(String valueUnit) {
		this.valueUnit = valueUnit;
	}
	
	public void setOperand(String operand)
	{
		this.operand = operand;
	}
	
	public String getOperand() {
		return this.operand;
	}
	
	public Set<Condition> getConditionCollection() {
		return this.conditionCollection;
	}

	public void setConditionCollection(Set<Condition> conditionCollection) {
		this.conditionCollection = conditionCollection;
	}

	public Finding getFinding() {
		return this.finding;
	}

	public void setFinding(Finding finding) {
		this.finding = finding;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

}
