package gov.nih.nci.cananolab.domain.common;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final


import gov.nih.nci.cananolab.domain.particle.SynthesisPurity;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PurityDatum generated by hbm2java
 */
public class PurityDatum implements java.io.Serializable {

	private Long datumPkId;
	private File file;
	private SynthesisPurity synthesisPurity;
	private String name;
	private Float value;
	private String valueType;
	private String valueUnit;
	private String createdBy;
	private Date createdDate;
	private String operand;
	private Set<Condition> experimentConditions = new HashSet<Condition>(0);

	public PurityDatum() {
	}

	public PurityDatum(long datumPkId, String name, Float value, String createdBy, Date createdDate) {
		this.datumPkId = datumPkId;
		this.name = name;
		this.value = value;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
	}

	public PurityDatum(long datumPkId, File file, SynthesisPurity synthesisPurity, String name, Float value, String valueType,
					   String valueUnit, String createdBy, Date createdDate, String operand, Set<Condition> experimentConditions) {
		this.datumPkId = datumPkId;
		this.file = file;
		this.synthesisPurity = synthesisPurity;
		this.name = name;
		this.value = value;
		this.valueType = valueType;
		this.valueUnit = valueUnit;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.operand = operand;
		this.experimentConditions = experimentConditions;
	}

	public Long getId() {
		return this.datumPkId;
	}

	public void setId(Long datumPkId) {
		this.datumPkId = datumPkId;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	public SynthesisPurity getSynthesisPurity() {
		return this.synthesisPurity;
	}

	public void setSynthesisPurity(SynthesisPurity synthesisPurity) {
		this.synthesisPurity = synthesisPurity;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getValue() {
		return this.value;
	}

	public void setValue(Float value) {
		this.value = value;
	}

	public String getValueType() {
		return this.valueType;
	}

	public void setValueType(String valueType) {
		this.valueType = valueType;
	}

	public String getValueUnit() {
		return this.valueUnit;
	}

	public void setValueUnit(String valueUnit) {
		this.valueUnit = valueUnit;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getOperand() {
		return this.operand;
	}

	public void setOperand(String operand) {
		this.operand = operand;
	}

	public Set<Condition> getConditionCollection() {
		return this.experimentConditions;
	}

	public void setConditionCollection(Set<Condition> experimentConditions) {
		this.experimentConditions = experimentConditions;
	}

}
