package gov.nih.nci.cananolab.domain.common;
// Generated Apr 3, 2019, 8:32:55 PM by Hibernate Tools 5.4.2.Final

import java.io.Serializable;

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements Serializable {

	private long supplierPkId;

	private String supplierName;
	private String lot;

	public Supplier() {
	}

	public Supplier(String supplierName) {
		this.supplierName = supplierName;
	}

	public Supplier(String supplierName, String lot) {
		this.supplierName = supplierName;
		this.lot = lot;
	}

	public long getId() {
		return this.supplierPkId;
	}

	public void setId(long supplierPkId) {
		this.supplierPkId = supplierPkId;
	}

	public String getSupplierName() {
		return this.supplierName;
	}

	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	public String getLot() {
		return this.lot;
	}

	public void setLot(String lot) {
		this.lot = lot;
	}

}
